OUTPUT_DIR: './result/resunet++/Oct13_1'
CHECKPOINT_PATH: '' #'./result/resunet++/Oct13_1/checkpoints/best_model.pt'

MODEL:
  IMAGE_SIZE: (448, 448)

TRAIN:
  AUGMENT: True
  SCHEDULER_PATIENCE: 10

DATA:
  ROOT_DIR: './data'
  TRAIN_IMAGES: 'train_images'
  TEST_IMAGES: 'test_images'
  TRAIN_MASKS: 'dfs_masks'
  
  TRAIN: 'train4.csv'
  VAL: 'val4.csv'
  
SOLVER:
  EPOCH: 200
  BATCH_SIZE: 4
  EARLY_STOPPING: -1
  LR: 0.001

INFERENCE:
  SAVE_DIR: './result/resunet++/Oct13_1'
  CRF_STEP: 5
  CRF: False

