OUTPUT_DIR: './result/resunet++/Oct16_2'
CHECKPOINT_PATH: '' #'./result/resunet++/Oct12_1/checkpoints/'

MODEL:
  IMAGE_SIZE: (256, 256)

TRAIN:
  AUGMENT: True
  SCHEDULER_PATIENCE: 6

DATA:
  ROOT_DIR: './data'
  TRAIN_IMAGES: 'train_images'
  TEST_IMAGES: 'test_images'
  TRAIN_MASKS: 'dfs_masks'
  
  TRAIN: 'train4.csv'
  VAL: 'val4.csv'
  
SOLVER:
  EPOCH: 200
  BATCH_SIZE: 12
  EARLY_STOPPING: -1
  LR: 0.001

INFERENCE:
  SAVE_DIR: './result/resunet++/Oct16_2'
  CRF_STEP: 5
  CRF: False
  MASK_THRES: 0.7


